### ISSUE TITLE
Error: Could not find file! 

### ISSUE THREAD

**Issue by behiunforgiven** [camalot/droidexplorer#64]
I want to open application database file with Droid Explorer but it can not open it.
my database located at :
`/data/data/<package-name>/databases/rollcall.db`
but I cant transfer it to my computer or open it with Db Browser For Sqlite.
with right click on the file it shows an error : "Error: Could not find file"

(My phone is rooted and Busybox is installed, I can access the file via es file explorer in phone.)

![photo_2018-01-31_16-32-20](https://user-images.githubusercontent.com/2098017/35624501-68492972-06a4-11e8-9973-3849712a5918.jpg)

**Comment by camalot** [comment]
can you open the debug windows, and supply the output from that when you try to open the file?

**Comment by behiunforgiven** [comment]
I installed the exe file and run the program, you mean run with visual studio and debug it?

**Comment by camalot** [comment]
No, in Droid explorer there is a little bug icon that will open a window
that shows some debug output.

**Comment by behiunforgiven** [comment]
Ok thanks,This is the error:

`
[TransferDialog] Attempted to divide by zero. - System.DivideByZeroException: Attempted to divide by zero.
   at DroidExplorer.Core.UI.TransferDialog.SpeedTest() in E:\Development\projects\csharp\droidexplorer\trunk\DroidExplorer\DroidExplorer.Core.UI\TransferDialog.cs:line 323
[Program] Length cannot be less than zero.
Parameter name: length - System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at DroidExplorer.Core.UI.CConsole.ConsoleControl.richTextBoxConsole_KeyDown(Object sender, KeyEventArgs e) in E:\Development\projects\csharp\droidexplorer\trunk\DroidExplorer\DroidExplorer.Core.UI\CConsole\ConsoleControl.cs:line 259
   at System.Windows.Forms.Control.OnKeyDown(KeyEventArgs e)
   at System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
   at System.Windows.Forms.Control.WmKeyChar(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.RichTextBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
[CommandRunner] adb.exe -s HT487WM00251 pull "/data/data/ir.behzadshirani.rollcall/databases/rollcall.db" "C:\Users\ms0740\AppData\Local\Temp\DroidExplorer\data.data.ir.behzadshirani.rollcall.databases.rollcall.db"
[TransferDialog] Could not find file 'C:\Users\ms0740\AppData\Local\Temp\DroidExplorer\data.data.ir.behzadshirani.rollcall.databases.rollcall.db'. - System.IO.FileNotFoundException: Could not find file 'C:\Users\ms0740\AppData\Local\Temp\DroidExplorer\data.data.ir.behzadshirani.rollcall.databases.rollcall.db'.
File name: 'C:\Users\ms0740\AppData\Local\Temp\DroidExplorer\data.data.ir.behzadshirani.rollcall.databases.rollcall.db'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.FileInfo.CopyTo(String destFileName, Boolean overwrite)
   at DroidExplorer.Core.UI.TransferDialog.<>c__DisplayClass23_0.<PrivatePull>b__0(Object o) in E:\Development\projects\csharp\droidexplorer\trunk\DroidExplorer\DroidExplorer.Core.UI\TransferDialog.cs:line 139
`

**Comment by behiunforgiven** [comment]
Ok thanks,This is the error:

`
[TransferDialog] Attempted to divide by zero. - System.DivideByZeroException: Attempted to divide by zero.
   at DroidExplorer.Core.UI.TransferDialog.SpeedTest() in E:\Development\projects\csharp\droidexplorer\trunk\DroidExplorer\DroidExplorer.Core.UI\TransferDialog.cs:line 323
[Program] Length cannot be less than zero.
Parameter name: length - System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at DroidExplorer.Core.UI.CConsole.ConsoleControl.richTextBoxConsole_KeyDown(Object sender, KeyEventArgs e) in E:\Development\projects\csharp\droidexplorer\trunk\DroidExplorer\DroidExplorer.Core.UI\CConsole\ConsoleControl.cs:line 259
   at System.Windows.Forms.Control.OnKeyDown(KeyEventArgs e)
   at System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
   at System.Windows.Forms.Control.WmKeyChar(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.RichTextBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
[CommandRunner] adb.exe -s HT487WM00251 pull "/data/data/ir.behzadshirani.rollcall/databases/rollcall.db" "C:\Users\ms0740\AppData\Local\Temp\DroidExplorer\data.data.ir.behzadshirani.rollcall.databases.rollcall.db"
[TransferDialog] Could not find file 'C:\Users\ms0740\AppData\Local\Temp\DroidExplorer\data.data.ir.behzadshirani.rollcall.databases.rollcall.db'. - System.IO.FileNotFoundException: Could not find file 'C:\Users\ms0740\AppData\Local\Temp\DroidExplorer\data.data.ir.behzadshirani.rollcall.databases.rollcall.db'.
File name: 'C:\Users\ms0740\AppData\Local\Temp\DroidExplorer\data.data.ir.behzadshirani.rollcall.databases.rollcall.db'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.FileInfo.CopyTo(String destFileName, Boolean overwrite)
   at DroidExplorer.Core.UI.TransferDialog.<>c__DisplayClass23_0.<PrivatePull>b__0(Object o) in E:\Development\projects\csharp\droidexplorer\trunk\DroidExplorer\DroidExplorer.Core.UI\TransferDialog.cs:line 139
`
